### ISSUE TITLE
Has easy to personalise URLs

### ISSUE THREAD

**Issue by ctford** [ctford/bienvenides#3]
AS someone from recruiting
I WANT to conveniently create a personalised link to _bienvenides_
SO THAT I can share it with someone that we hope will join Thoughtworks

Implementation idea: a separate URL that presents a form field.

**Comment by vitor-barbosa-tw** [comment]
New url used to create a personal link: https://vitor-barbosa-tw.github.io/bienvenides/#/url-generator
