### ISSUE TITLE
Pushed to Github pages

### ISSUE THREAD

**Issue by ctford** [ctford/bienvenides#4]
AS someone updating the tool
I WANT a repeatable process to build _bienvenides_ to Github pages
SO THAT it's convenient and secure to share it with people outside of Thoughtworks

Implementation idea: a Github action that runs the build and pushes successful changes to the `gh-pages` branch.

**Comment by vitor-barbosa-tw** [comment]
Already deployed to github pages on every commit to master via github actions: https://vitor-barbosa-tw.github.io/bienvenides/#/?name=Vitor%20Quintanilha%20Barbosa
